---
- name: prepare os and install docker
  hosts: base
  become: true
  roles:
    - prep_os
    - prep_docker

- name: install portainer, watchtower, nextcloud, traefik
  hosts: app
  # become: true
  become_user: "{{ansible_user}}"
  roles:
   - prep_traefik
   - prep_portainer
   - prep_watchtower
   - prep_nextcloud

