---
# run systemspecific tasks on RHEL

  - name: Update cache and all packages on RHEL
    tags: always 
    ansible.builtin.dnf:
      update_cache: yes
      name:
        - "*"
      state: latest

  - name: permit traffic in default zone for ssh service
    ansible.posix.firewalld:
      service: "{{ item }}"
      permanent: true
      state: enabled
    with_items:
      - "{{ ssh_port }}"
