--- 
- name: Create a network
  community.docker.docker_network:
    name: "{{nextcloud_network}}"

- name: Download and deploy nextcloud docker container
  community.docker.docker_container:
    name: mariadb
    image: mariadb
    restart_policy: unless-stopped
    volumes:
      - "{{mariadb_volume}}:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: testtest
      MYSQL_PASSWORD: testtest
      MYSQL_DATABASE: nextcloud
      MYSQL_USE: nextcloud
    networks:
      - name: "{{nextcloud_network}}"
  


- name: Download and deploy nextcloud docker container
  community.docker.docker_container:
    name: nextcloud
    image: nextcloud
    restart_policy: unless-stopped
    ports: 
      - "8080:80"
    volumes: 
      - "{{nextcloud_volume}}:/var/www/html"
    links: 
      - "{{mariadb_volume}}:/var/lib/mysql"
    env:
      MYSQL_PASSWORD: testtest
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
    networks:
      - name: "{{nextcloud_network}}"
