---
- name: "run portainer installation"
  # become: True
  # become_user: "{{ ansible_user_id }}"
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce
    # ports:
    #   - "9443:9443"
    #   - "8000:8000"
    restart_policy: "unless-stopped"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/container/portainer:/data
    labels: 
      traefik.enable: "true"
      traefik.http.routers.portainer.rule: "Host(`port.test.dhull.eu`)"
    networks:
      - name: "{{traefik_network}}"